services:
  - type: web
    name: anavai-go
    runtime: go
    rootDir: .
    buildCommand: go build -ldflags="-s -w" -o anavai-server .
    startCommand: ./anavai-server
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
